/***/

#ifndef PLATFORM_SENSEBE_TX_REV1_H_
#define PLATFORM_SENSEBE_TX_REV1_H_

#define LED_RED_PIN		GPIO_BSRR_BS_6
#define LED_RED_PORT		GPIOA
#define LED_GREEN_PIN		GPIO_BSRR_BS_7
#define LED_GREEN_PORT		GPIOA
#define LEDS_ACTIVE_STATE	GPIO_BSRR_BS_1

#define BUTTON_PIN		GPIO_BSRR_BS_1
#define BUTTON_PORT		GPIOA
#define BUTTON_ACTIVE_STATE	0

#define LIGHT_SENSE_PIN		GPIO_BSRR_BS_4
#define LIGHT_SENSE_PORT	GPIOA

#define LEDIR_PWR1_PIN		GPIO_BSRR_BS_9
#define LEDIR_PWR1_PORT		GPIOA

#define LEDIR_PWR2_PIN		GPIO_BSRR_BS_0
#define LEDIR_PWR2_PORT		GPIOA

#define LEDIR_PWR3_PIN		GPIO_BSRR_BS_1
#define LEDIR_PWR3_PORT		GPIOB

#define LEDIR_CTRL1_PIN		GPIO_BSRR_BS_10
#define LEDIR_CTRL1_PORT	GPIOA

#define LEDIR_CTRL2_PIN		GPIO_BSRR_BS_5
#define LEDIR_CTRL2_PORT	GPIOA


#endif //PLATFORM_SENSEBE_TX_REV1_H_
